version: '3'

services:
  backend:
    image: dastou/backend:v1.0.0
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/db.sqlite3
    environment:
      - DEBUG=True

volumes:
  sqlite_data: